
apiVersion: batch/v1
kind: CronJob
...
spec:
  ...
  jobTemplate:
    spec:
      ...
      template:
        ...
        spec:
          ...
          restartPolicy: Never
          #============ Init containers ============
          initContainers:
            - name: init
              image: ...
              ...
              command: [ "init-container" ]
              env:
                - name: CTOOLS_ROLE
                  value: cron
                - name: DB_URL
                  value: ...
                - name: DB_CA_CERT_URL
                  value: ...
                ...
              volumeMounts:
                - mountPath: "/tmp"
                  name: tmpdir
                ...

          #============ Containers ============
          containers:
            - name: phpcron
              image: ...
              imagePullPolicy: IfNotPresent
              env:
                - name: CTOOLS_ROLE
                  value: cron
                - name: DB_URL
                  value: ...
                - name: CRON_JOB
                  value: ...
                - name: CRON_SYMFONY_CMD
                  value: ...
                - name: CRON_CMD_OPTS
                  value: ...
                ...
              volumeMounts:
                - mountPath: "/tmp"
                  name: tmpdir
                ...
          volumes:
            - name: tmpdir
              emptyDir: {}
            ...
---
