
apiVersion: apps/v1
kind: Deployment
...
spec:
  ...
  template:
    ...
    spec:
      ...
      #============ Init containers ============
      initContainers:
        - name: init
          image: ...
          ...
          command: [ "init-container" ]
          env:
            ...
          volumeMounts:
            - mountPath: "/tmp"
              name: tmpdir
            ...

      #============ Containers ============
      containers:
        - name: main
          image: ...
          env:
            ...
          volumeMounts:
            - mountPath: "/tmp"
              name: tmpdir
            ...

      volumes:
        - name: tmpdir
          emptyDir: {}
        ...
